Repository BuildForSDG/Team-028-Product, pull requests merged in 2020-06, with the labels that each got.

#86 Projects
  src/frontend/src/components/dashboard/admin/AdminDashboard.js
  src/frontend/src/components/dashboard/admin/category/Create.js
  src/frontend/src/components/dashboard/admin/category/Delete.js
  src/frontend/src/components/dashboard/admin/category/Update.js
  src/frontend/src/components/dashboard/admin/category/View.js
  src/frontend/src/components/dashboard/admin/projects/Create.js
  src/frontend/src/components/dashboard/admin/projects/View.js
  src/frontend/src/components/dashboard/admin/projects/ViewDetails.js
Labels: enhancement

#91 Feat: created sigin and signup module
  src/backend/config/env.js
  src/frontend/src/components/dashboard/admin/projects/Create.js
  src/frontend/src/components/dashboard/admin/projects/View.js
  src/frontend/src/components/header/Nav.js
  src/frontend/src/components/header/Registration.js
Labels: enhancement

#102 Ft search
  src/frontend/src/components/dashboard/admin/projects/View.js
  src/frontend/src/components/dashboard/investor/InvestmentHistory.js
  src/frontend/src/components/dashboard/investor/SmeProposals.js
  src/frontend/src/components/dashboard/investor/projects/View.js
  src/frontend/src/components/dashboard/regulator/Investors.js
  src/frontend/src/components/dashboard/regulator/Projects.js
  src/frontend/src/components/dashboard/regulator/SMEs.js
  src/frontend/src/styles/index.css
  yarn.lock
Labels: enhancement

#103 Cleanup
  src/backend/app.js
  src/backend/controller/user.controller.js
  src/backend/controller/userLogin.controller.js
  src/backend/controller/userOrganisation.controller.js
  src/backend/model/organization.model.js
  src/backend/model/user.model.js
  src/backend/model/userLoggin.model.js
  src/frontend/src/components/header/Nav.js
  src/frontend/src/components/header/Registration.js
Labels: duplicate

#108 Feature fe
  src/frontend/src/components/content/Content.js
  src/frontend/src/components/header/Login.js
Labels: enhancement

#113 Login_Project View Fixtures
  src/backend/app.js
  src/backend/config/env.js
  src/backend/controller/projectCategory.controller.js
  src/backend/controller/userLogin.controller.js
  src/frontend/public/manifest.json
  src/frontend/src/components/carousel/Carousel.js
  src/frontend/src/components/content/Content.js
  src/frontend/src/components/dashboard/admin/category/View.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/investor/TotalInvestments.js
  src/frontend/src/components/dashboard/regulator/RegulatorDashboard.js
  src/frontend/src/components/dashboard/sme/SmeDashboard.js
  src/frontend/src/components/footer/Footer.js
  src/frontend/src/components/header/About.js
  src/frontend/src/components/header/Header.js
  src/frontend/src/components/header/Login.js
  src/frontend/src/components/header/Nav.js
  src/frontend/src/history.js
  src/frontend/src/index.js
Labels: enhancement

#119 fix: uniform search bar across all dashboards
  src/frontend/src/components/dashboard/admin/AdminDashboard.js
  src/frontend/src/components/dashboard/admin/category/View.js
  src/frontend/src/components/dashboard/admin/projects/View.js
  src/frontend/src/components/dashboard/general/View.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/regulator/Investors.js
  src/frontend/src/components/dashboard/regulator/Projects.js
  src/frontend/src/components/dashboard/regulator/SMEs.js
  src/frontend/src/components/dashboard/sme/Funds/Proposal.js
  src/frontend/src/components/dashboard/sme/Projects/FundedProjects.js
  src/frontend/src/components/dashboard/sme/Projects/InvestmentProject.js
  src/frontend/src/styles/index.css
Labels: enhancement

#123 Ft create investments
  src/backend/app.js
  src/backend/config/env.js
  src/backend/controller/funds.controller.js
  src/backend/routes/funds.route.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/investor/invest.js
  src/frontend/src/components/dashboard/investor/projects/Create.js
Labels: enhancement

#127 Ft view investments history
  src/backend/controller/funds.controller.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/investor/TotalInvestments.js
  src/frontend/src/components/dashboard/investor/invest.js
Labels: enhancement

#129 ft: Sync create user to db
  src/backend/config/env.js
  src/backend/controller/milestone.controller.js
  src/backend/controller/user.controller.js
  src/backend/controller/userLogin.controller.js
  src/backend/routes/milestone.route.js
  src/backend/routes/user.route.js
  src/frontend/src/components/dashboard/admin/projects/CreateEligibility.js
  src/frontend/src/components/dashboard/general/CreateUser.js
  src/frontend/src/components/dashboard/general/Update.js
  src/frontend/src/components/dashboard/sme/Funds/NewApplication.js
  src/frontend/src/components/dashboard/sme/Funds/UpdateMilestone.js
  src/frontend/src/components/dashboard/sme/Funds/ViewMilestones.js
  src/frontend/src/components/dashboard/sme/Projects/Milestones.js
  src/frontend/src/components/dashboard/sme/SmeDashboard.js
  src/frontend/src/components/header/Nav.js
Labels: enhancement

#131 Ft view investment history
  src/backend/app.js
  src/backend/controller/fundDisbursment.controller.js
  src/backend/model/disbursment.model.js
  src/backend/routes/fundDisbursment.route.js
  src/frontend/src/components/dashboard/investor/InvestmentHistory.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/investor/TotalInvestments.js
  src/frontend/src/components/dashboard/regulator/Projects.js
Labels: enhancement

#153 Ft change project status on creating investments
  src/backend/app.js
  src/backend/config/env.js
  src/backend/controller/funds.controller.js
  src/backend/model/project.model.js
  src/frontend/src/components/dashboard/investor/invest.js
Labels: documentation

#157 different dashboards color fixes
  src/frontend/src/components/dashboard/Dashboard.css
  src/frontend/src/components/dashboard/admin/AdminDashboard.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/regulator/RegulatorDashboard.js
  src/frontend/src/components/dashboard/sme/SmeDashboard.js
Labels: enhancement

#168 adding stying for the sme dashboard
  src/frontend/src/components/dashboard/Dashboard.css
Labels: enhancement

#169 Fix: broken code
  src/frontend/src/index.js
Labels: bug

#171 Presubmission
  src/backend/config/env.js
  src/backend/controller/fundApplication.controller.js
  src/backend/controller/funds.controller.js
  src/backend/controller/project.controller.js
  src/backend/controller/user.controller.js
  src/backend/model/fundApplication.model.js
  src/backend/model/project.model.js
  src/backend/routes/fundApplication.route.js
  src/frontend/src/components/dashboard/admin/AdminDashboard.js
  src/frontend/src/components/dashboard/admin/InvestorsAndFunding.js
  src/frontend/src/components/dashboard/admin/ProjectDetails.js
  src/frontend/src/components/dashboard/admin/SmeAndProjects.js
  src/frontend/src/components/dashboard/admin/projects/Create.js
  src/frontend/src/components/dashboard/general/Create.js
  src/frontend/src/components/dashboard/general/CreateUser.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/investor/ProjectDetails.js
  src/frontend/src/components/dashboard/investor/TotalInvestments.js
  src/frontend/src/components/dashboard/investor/projects/ViewDetails.js
  src/frontend/src/components/dashboard/sme/Funds/NewApplication.js
  src/frontend/src/components/dashboard/sme/Projects/FundedProjects.js
  src/frontend/src/components/dashboard/sme/Projects/Milestones.js
  src/frontend/src/components/dashboard/sme/SmeDashboard.js
  src/frontend/src/components/header/Nav.js
Labels: enhancement

#175 Fix: login feature
  src/frontend/src/components/RecoverPassword.js
  src/frontend/src/components/dashboard/admin/InvestorsAndFunding.js
  src/frontend/src/components/dashboard/admin/ProjectDetails.js
  src/frontend/src/components/dashboard/admin/SmeAndProjects.js
  src/frontend/src/components/dashboard/admin/category/Create.js
  src/frontend/src/components/dashboard/admin/category/InvestmentCategory.js
  src/frontend/src/components/dashboard/admin/category/Update.js
  src/frontend/src/components/dashboard/admin/category/View.js
  src/frontend/src/components/dashboard/admin/funds/ViewFunds.js
  src/frontend/src/components/dashboard/admin/projects/Create.js
  src/frontend/src/components/dashboard/admin/projects/CreateEligibility.js
  src/frontend/src/components/dashboard/admin/projects/View.js
  src/frontend/src/components/dashboard/admin/projects/ViewDetails.js
  src/frontend/src/components/dashboard/general/Create.js
  src/frontend/src/components/dashboard/general/CreateUser.js
  src/frontend/src/components/dashboard/general/Update.js
  src/frontend/src/components/dashboard/general/View.js
  src/frontend/src/components/dashboard/investor/FundDetails.js
  src/frontend/src/components/dashboard/investor/InvestorDashboard.js
  src/frontend/src/components/dashboard/investor/ProjectDetails.js
  src/frontend/src/components/dashboard/investor/SmeProposals.js
  src/frontend/src/components/dashboard/investor/TotalInvestments.js
  src/frontend/src/components/dashboard/investor/invest.js
  src/frontend/src/components/dashboard/investor/projects/View.js
  src/frontend/src/components/dashboard/investor/projects/ViewDetails.js
  src/frontend/src/components/dashboard/investor/user/AllUsers.js
  src/frontend/src/components/dashboard/sme/Funds/NewApplication.js
  src/frontend/src/components/dashboard/sme/Funds/Proposal.js
  src/frontend/src/components/dashboard/sme/Funds/UpdateMilestone.js
  src/frontend/src/components/dashboard/sme/Funds/ViewMilestones.js
  src/frontend/src/components/dashboard/sme/Projects/FundedProjects.js
  src/frontend/src/components/dashboard/sme/Projects/InvestmentProject.js
  src/frontend/src/components/dashboard/sme/Projects/Milestones.js
  src/frontend/src/components/dashboard/sme/SmeDashboard.js
  src/frontend/src/components/header/Login.js
  src/frontend/src/components/header/Nav.js
  src/frontend/src/components/header/Registration.js
Labels: enhancement
